### ISSUE TITLE
128K Fairlight .z80 files don't run on real hardware

### ISSUE THREAD

**Issue by ghost** [skoolkid/t2sfiles#10]
The .z80 files resulting from the Fairlight and Fairlight II 128K ts2 files appear to run on emulators but crash or hang on real hardware. No issues found with the 48K files.

Fairlight 128k corrupts the screen, re-starting the tune at each keypress until the computer resets.

Fairlight II hangs with a Green border on completing the load and keypresses are not registered, so the game cannot be started.

Tested on a 128K toastrack, Grey 128K +2 and a 128K Harlequin with the same result on each.

**Comment by skoolkid** [comment]
Hi. How are you loading the Z80 snapshots on real hardware?

**Comment by ghost** [comment]
HiI’m loading them from a ByteDelight DIVMMC Enjoy Pro.On 5 Feb 2024, at 13:34, Richard Dymond ***@***.***> wrote:﻿
Hi. How are you loading the Z80 snapshots on real hardware?

**Comment by TomDDG** [comment]
I've just tested both (created using the t2s) on my Microdrive Emulator using the inbuilt Z80 loader and they work fine on my toastrack 128k. Best guess is they don't load due to the way the DivMMC handles 128k snapshots.

If you do want to load via a DivMMC you can always convert the TZX to Z80 and then to a TAP using my Z80onTAP conversion utility (https://tomdalby.com/other/files/Z80onTAP.zip). This uses the same routine as the one for the Microdrive.
